# Generated by Django 5.2.3 on 2025-06-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibemusic', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='genre',
            name='icon',
            field=models.CharField(choices=[('rock.png', 'Рок'), ('pop.png', 'Поп'), ('jazz.png', 'Джаз'), ('classical.png', 'Классика'), ('hiphop.png', 'Хип-хоп'), ('electric.png', 'Электроника'), ('indie.png', 'Инди')], default='default.png', max_length=50, verbose_name='Иконка жанра'),
        ),
    ]
