# Generated by Django 5.2.3 on 2025-06-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibemusic', '0004_post_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, max_length=255, verbose_name='Биография'),
        ),
    ]
