# Generated by Django 5.2.3 on 2025-07-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibemusic', '0004_artist_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='Изображение шапки сайта')),
            ],
            options={
                'verbose_name': 'Настроки сайта',
                'verbose_name_plural': 'Настроки сайта',
            },
        ),
    ]
