# Generated by Django 5.2.3 on 2025-06-29 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibemusic', '0007_alter_artist_bio_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='icon',
            field=models.CharField(choices=[('rock.png', 'Рок'), ('pop.png', 'Поп'), ('jazz.png', 'Джаз'), ('classical.png', 'Классика'), ('hiphop.png', 'Хип-хоп'), ('electric.png', 'Электроника'), ('indie.png', 'Инди'), ('folk-rock', 'фолк-рок'), ('indie-folk', 'инди-фолк')], default='default.png', max_length=50, verbose_name='Иконка жанра'),
        ),
        migrations.AlterField(
            model_name='post',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='vibemusic.artist', verbose_name='Исполнитель'),
        ),
    ]
