# Generated by Django 5.2.3 on 2025-06-29 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibemusic', '0008_alter_genre_icon_alter_post_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='track',
            name='is_downloadable',
        ),
        migrations.RemoveField(
            model_name='track',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='track',
            name='album_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение альбома'),
        ),
        migrations.AddField(
            model_name='track',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='track_set', to='vibemusic.post', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vibemusic.artist', verbose_name='Исполнитель'),
        ),
    ]
