# Generated by Django 5.2.3 on 2025-07-02 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vibemusic', '0009_remove_track_duration_remove_track_is_downloadable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='post',
        ),
    ]
