# Generated by Django 5.2.3 on 2025-07-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibemusic', '0010_remove_track_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='genre_backgrounds/', verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='genre_icons/', verbose_name='Иконка жанра'),
        ),
    ]
