# Generated by Django 5.2.3 on 2025-07-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibemusic', '0011_genre_background_image_alter_genre_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='related_genres',
            field=models.ManyToManyField(blank=True, to='vibemusic.genre', verbose_name='Связанные жанры'),
        ),
    ]
