# Generated by Django 5.2.3 on 2025-09-12 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vibemusic', '0014_profile_photo_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo_number',
            new_name='phone_number',
        ),
    ]
