"""
Django settings for coolsite project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hg6$tpf#c@m0x%r1fscanm@n*=0q7lli@4n0lr!(!9_a^%6#yw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['localhost', '127.0.0.1',  '192.168.100.33']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'captcha',
    'crispy_forms',
    'crispy_bootstrap5',
    'widget_tweaks',
    'vibemusic.apps.VibemusicConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'coolsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Папка с общими шаблонами
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'coolsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'vibemusic/static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# учетные данные Spotify:
# Для чтения метаданных из MP3-файлов устанавливаем библиотеку mutagen:
SPOTIFY_CLIENT_ID = "9b9eedb0308a4800afcfab8a04618ee8"
SPOTIFY_CLIENT_SECRET = "1654b0a4ed9441989c8439f0039d9d9b"

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Или 'bootstrap4', если используете старую версию
CRISPY_TEMPLATE_PACK = 'bootstrap5'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DEFAULT_ALBUM_IMAGE = 'image/default_album.jpg'

# Pagination settings
COMMENTS_PER_PAGE = 5  # Количество комментариев на страницу
POSTS_PER_PAGE = 5     # Количество постов на страницу

# Authentication redirects
LOGIN_REDIRECT_URL = 'vibemusic:home'  # Перенаправление после входа
LOGOUT_REDIRECT_URL = 'vibemusic:home'  # Перенапровление после выхода 


# Обработка отправки писем для сброса пароля, настройки SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'           # Django будет использовать SMTP-сервер для отправки писем (например, Gmail, Yandex, Mailgun, либо корпоративный сервер). 
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'artem.flowers1@gmail.com'                           # Ваш реальный email
EMAIL_HOST_PASSWORD = 'qhns odzq gjxs rljx'                          # Пароль приложения Gmail
DEFAULT_FROM_EMAIL = 'artem.flowers1@gmail.com'
TELEGRAM_BOT_TOKEN = '8311811025:AAGB7PfqMPakk2a68EIhhf4fmygpZh1xf7g'   # Токен телеграмм бота
TELEGRAM_BOT_USERNAME = 'VibeMusicResetBot'                           # Username бота без @

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'        # Отправка в консоль для сообщения 


# Логирование для отладки 
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#         },
#         'vibemusic': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#             'propagate': False,
#         },
#     },
# }
