# Generated by Django 5.2.3 on 2025-07-04 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/', verbose_name='Фотография')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись к фото')),
            ],
            options={
                'verbose_name': 'Фотография поста',
                'verbose_name_plural': 'Фотография постов',
            },
        ),
        migrations.CreateModel(
            name='UserProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название жанра')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='genre_icons/', verbose_name='Иконка жанра')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='genre_backgrounds/', verbose_name='Фоновое изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание жанра')),
                ('related_genres', models.ManyToManyField(blank=True, to='vibemusic.genre', verbose_name='Связанные жанры')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Имя исполнителя')),
                ('bio', models.TextField(blank=True, max_length=7000, verbose_name='Биография')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='artist_photos/', verbose_name='Фото исполнителя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('genres', models.ManyToManyField(related_name='artists', to='vibemusic.genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок поста')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Содержимое поста')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='vibemusic.artist', verbose_name='Исполнитель')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='vibemusic.genre', verbose_name='Жанр')),
                ('images', models.ManyToManyField(blank=True, related_name='posts', to='vibemusic.postimage', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='vibemusic.comment', verbose_name='Родительский комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vibemusic.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название трека')),
                ('audio_file', models.FileField(upload_to='tracks/', verbose_name='Аудиофайл')),
                ('album_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение альбома')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vibemusic.artist', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='posts', to='vibemusic.track', verbose_name='Треки'),
        ),
    ]
