# Generated by Django 5.2.3 on 2025-07-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibemusic', '0005_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='site_settings/', verbose_name='Изображение шапки'),
        ),
    ]
