# Generated by Django 5.2.3 on 2025-08-05 22:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibemusic', '0009_reaction_delete_userprof_alter_postimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки'),
        ),
    ]
