# Generated by Django 5.2.3 on 2025-08-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibemusic', '0010_alter_postimage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='album_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название альбома'),
        ),
    ]
