# Generated by Django 5.2.3 on 2025-09-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibemusic', '0011_track_album_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username (без @)'),
        ),
    ]
