# Generated by Django 5.2.3 on 2025-09-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibemusic', '0012_profile_telegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Идентификатор чата Telegram (ID)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя пользователя Telegram (с @)'),
        ),
    ]
