# Generated by Django 5.2.3 on 2025-09-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibemusic', '0013_profile_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
    ]
