# Generated by Django 5.2.3 on 2025-09-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibemusic', '0015_rename_photo_number_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='vibemusic.profile', verbose_name='Подписки'),
        ),
    ]
